version: '3.7'
services:
  mysql:
    image: mysql:8.0.18
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DB=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  node:
    image: node:16-alpine
    user: "node"
    ports:
      - '9999:9999'
    working_dir: /app
    volumes:
      - ./gate-simulator/:/app
    command: "npm start"
